### ISSUE TITLE
If the site implements other payment methods. There's a bug that causes the app to throw a 500

### ISSUE THREAD

**Issue by gogo52cn** [amzn/spree_pay_with_amazon#16]
If the site implements other payment method. There's a bug that causes the app to throw a 500.

when the customer is not checking out with amazon at the cart page and clicks "checkout", he will be redirecting to the normal payment page. this view asks for a spree/checkout/payment/_amazon partial but it doesn't exists....

**Comment by MattDunbar** [comment]
I have identified the issue here.

When you create the Amazon payment method it should be set to Backend only, not Both.
