### ISSUE TITLE
3-0-stable branch

### ISSUE THREAD

**Issue by mleglise** [amzn/spree_pay_with_amazon#19]
Any plans to make a 3-0-stable branch?

**Comment by ngrices** [comment]
@mleglise Yes! Just waiting for demand like this. Are you a developer or do you run your own store?

**Comment by killy** [comment]
@ngrices we've fixed the gem for Spree 3.0 - would like to send you the pull request this week after some cleanup, ok? :)

https://github.com/spark-solutions/spree_pay_with_amazon

**Comment by mleglise** [comment]
@ngrices I'm a dev, exploring the possibilities. Extensions like this are *super* useful, as long as they include a good test suite and are kept up to date.
Glad to see @killy is on top of it.

**Comment by killy** [comment]
@ngrices pull request sent https://github.com/amzn/spree_pay_with_amazon/pull/20

**Comment by ngrices** [comment]
merged PR #20
