### ISSUE TITLE
Spree Core Engine mount path breaks Pay with Amazon checkout pipeline 

### ISSUE THREAD

**Issue by khoja-Amazon** [amzn/spree_pay_with_amazon#7]
If you change the Spree Core Engine mount path to anything besides the domain root, it breaks the Pay with Amazon checkout pipeline. 

Example:
change path in config/routes.rb:

mount Spree::Core::Engine, :at => '/mystore'

**Comment by MattDunbar** [comment]
Merged in pull requests on all branches.
