### ISSUE TITLE
Onepage checkout : showing front page products under widgets

### ISSUE THREAD

**Issue by ngrices** [amzn/spree_pay_with_amazon#9]
![screen shot 2015-02-03 at 3 39 08 pm](https://cloud.githubusercontent.com/assets/7907929/6032182/05e9d656-abbb-11e4-919a-41d2ff3838b9.png)

**Comment by marchtemp** [comment]
Shipping section renders only after the user clicks on the widget.

**Comment by MattDunbar** [comment]
@ngrices @marchtemp Could you confirm if this is happening on every request, or if you're aware of what's triggering it? I haven't been able to replicate yet but will continue to try.

Regarding waiting for the user to click on the widget, I'll look into what options we have here.

**Comment by marchtemp** [comment]
@MattDunbar the shipping section takes 2-3 seconds to load (my environment is slow, however, it may also be an issue for some merchants). 
Clicking on the widget reloads the shipping section. It can be confusing, since there's no placeholder telling the user that it is loading.

**Comment by MattDunbar** [comment]
@marchtemp Load speed is definitely environment specific, we aren't doing anything that'd cause content to load particularly slow and it loads relatively fast on my end. There is always some slowdown on this step if you're using live rates, but there isn't much we can do about that.

I'm looking into what we can hook into to get the shipping options loaded as soon as the widgets are ready.

I'll also look into possibly adding a loading indicator of some sort.



Regarding the home page loading in the delivery spot - please provide further details if at all possible.

**Comment by marchtemp** [comment]
@MattDunbar 
> home page loading in the delivery spot
I have replicated it in Safari and Firefox in your env https://spreesocialtest.buildrx.com/
It's the same as in Nathan's screenshot and it makes it impossible to proceed with the checkout. FYI, I was not logged in as admin.

**Comment by MattDunbar** [comment]
@marchtemp We'll look into this and resolve it tomorrow.

**Comment by MattDunbar** [comment]
Fixed on all branches.
